### ISSUE TITLE
未能找到类型或命名空间名“IChatUser”(是否缺少 using 指令或程序集引用?)

### ISSUE THREAD

**Issue by liangshaojiang** [jihadkhawaja/MobileChat#44]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	CS0246	未能找到类型或命名空间名“IChatUser”(是否缺少 using 指令或程序集引用?)		d:\Project\Test\Xamarin\MobileChat\src\MobileChat.MAUI\Shared\MainLayout.razor	4

**Comment by jihadkhawaja** [comment]
@liangshaojiang Thanks for reporting this, just add the missing using namespace. I'll fix it today.

**Comment by jihadkhawaja** [comment]
https://github.com/jihadkhawaja/MobileChat/pull/45
